### ISSUE TITLE
Error on compile, newest commit form master

### ISSUE THREAD

**Issue by TorchwoodPL** [ServUO/ServUO#1349]
```
Scripts: Compiling C# scripts...Failed with: 2 errors, 0 warnings
Errors:
 + Items/Quest/CrystalBallOfKnowledge.cs:
    CS0117: Line 100: W elemencie "Server.Utility" brak definicji "FixMinMax".
 + Services/Expansions/Time Of Legends/AuctionSafe/Gumps.cs:
    CS0117: Line 348: W elemencie "Server.Utility" brak definicji "ToInt64".
    CS0117: Line 349: W elemencie "Server.Utility" brak definicji "ToInt64".
    CS0117: Line 391: W elemencie "Server.Utility" brak definicji "ToInt64".
    CS0117: Line 392: W elemencie "Server.Utility" brak definicji "ToInt64".
    CS0117: Line 556: W elemencie "Server.Utility" brak definicji "ToInt64".
    CS0117: Line 563: W elemencie "Server.Utility" brak definicji "ToInt64".
Scripts: One or more scripts failed to compile or no script files were found.
Done in 42.12s.
```
